module.exports = {
  adminRoles: ['superadmin', 'manager', 'executive'],
  leadStatuses: [
    'New Lead',
    'Contact Attempted',
    'Interested',
    'Test Drive Scheduled',
    'Negotiation',
    'Booked',
    'Lost',
    'Dormant',
  ],
  testDriveStatuses: ['Pending', 'Scheduled', 'Completed', 'Cancelled', 'No Show'],
  enquiryStatuses: ['Open', 'In Progress', 'Responded', 'Closed'],
  productModels: ['VF 6', 'VF 7', 'Both'],
  enquiryInterests: [
    'General Enquiry',
    'Get On-Road Price',
    'Book Test Drive',
    'Finance Support',
    'Exchange Car',
    'Corporate/Fleet',
    'Service',
  ],
  resourceTypes: ['image', 'video'],
};
